name: Model Training CICD

permissions:
  id-token: write
  contents: write

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Train Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          pip install -r requirements.txt
          python train_model.py

          echo "## Model Scores" > report.md
          cat scores.txt >> report.md

          echo "## Confusion Matrix & Feature Importance" >> report.md
          echo '![](./ConfusionMatrix.png)' >> report.md
          echo '![](./FeatureImportance.png)' >> report.md

          cml comment create report.md
